##version  nginx-1.15.8

#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       4201;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
		
		location / {
            root "D:/PhilipsProject/ng-philips/dist/ng-philips";
            #try_files $uri $uri/ /index.html;
			#try_files $uri $uri/ /index.html =404;
			index  index.html;
        }
		
		location  /act/ {
            proxy_pass http://localhost:9090;
		
        }
		
		location  /mock/ {
            proxy_pass http://localhost:3000/;
        }
    }
}
