import {
  PreOrderComponent,
  PreorderexamineComponent,
  PreOrderoaComponent,
  ContractComponent,
  ContractExamineComponent,
  OrdersummaryBaseInfoComponent,
  OitcompleteComponent,
  ContractSignComponent,
} from "./pages";
import {
  PreBaseInfoTableComponent,
  PreProductComponent,
  PreProductTableComponent,
  PreBaseInfoFromComponent,
  SelectDealerComponent,
  SelectUserComponent,
  ApplyRemarksComponent,
  ContractRemarksComponent,
  OaAddInfoComponent,
  OitFormGroupComponent,
  ContractSignInfoComponent,
  OrdersummaryVerificationComponent,
  WinCheckTableComponent,
  OptionTableComponent,
  ThirdCheckInfoComponent,
  RealTimeInfoComponent,
  ConfirmComponent,
  ChangOrderPopupComponent,
  ApproveChangeComponent,
  SofonFileComponent,
  PdfPreviewComponent,
  StandardTableComponent,
  SelectPrebookComponent,
  SelectRefnoComponent,
  SelectNmpaComponent,
  ApprovalHistoryComponentOit,
  SignatureUploadComponent,
  ApprovalHistorySignatureComponent,
  EsignButtonComponent,
  SofonFileUploadComponent
} from "./components";
export * from "./pages";
export * from "./components";
export const PAGES = [
  PreOrderComponent,
  PreorderexamineComponent,
  PreOrderoaComponent,
  ContractComponent,
  ContractExamineComponent,
  OrdersummaryBaseInfoComponent,
  OitcompleteComponent,
  ContractSignComponent,
  SelectPrebookComponent,
];

export const COMPONENTS = [
  PreBaseInfoTableComponent,
  PreProductComponent,
  PreProductTableComponent,
  PreBaseInfoFromComponent,
  SelectDealerComponent,
  SelectUserComponent,
  ApplyRemarksComponent,
  ContractRemarksComponent,
  OaAddInfoComponent,
  OitFormGroupComponent,
  ContractSignInfoComponent,
  OrdersummaryVerificationComponent,
  WinCheckTableComponent,
  OptionTableComponent,
  ThirdCheckInfoComponent,
  RealTimeInfoComponent,
  ConfirmComponent,
  ChangOrderPopupComponent,
  ApproveChangeComponent,
  SofonFileComponent,
  PdfPreviewComponent,
  StandardTableComponent,
  SelectRefnoComponent,
  SelectNmpaComponent,
  ApprovalHistoryComponentOit,
  SignatureUploadComponent,
  ApprovalHistorySignatureComponent,
  EsignButtonComponent,
  SofonFileUploadComponent
];
